name: Deploy to Railway
on:
  workflow_dispatch:
jobs:
  deploy-to-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Deploy to Railway
        run: |
          ls
          cd backend
          railway up --service jasper-final-project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}